#!/bin/bash

echo installing prerequisites
apt install -y apache2 php mariadb-server libapache2-mod-php php-gmp php-curl php-intl php-mbstring php-xmlrpc php-mysql php-gd php-xml php-cli php-zip curl git composer gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils

echo securing mariadb
echo setting mariadb root password
mysql --user="root" --password="" --execute="SET PASSWORD FOR 'root'@'localhost' = PASSWORD('invoiceninja');"

echo removing anonymous users
mysql --user="root" --password="" --execute="DELETE FROM mysql.user WHERE User='';"

echo disabling remote root logins
mysql --user="root" --password="" --execute="DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"

echo removing test database
mysql --user="root" --password="" --execute="DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';"

echo flushing privileges
mysql --user="root" --password="" --execute="FLUSH PRIVILEGES;"

echo configuring php
sed -i -e 's/short_open_tag = Off/short_open_tag = On/g' /etc/php/7.3/apache2/php.ini
sed -i -e 's/memory_limit = 128M/memory_limit = 256M/g' /etc/php/7.3/apache2/php.ini
sed -i -e 's/upload_max_filesize = 2M/upload_max_filesize = 100M/g' /etc/php/7.3/apache2/php.ini
sed -i -e 's/max_execution_time = 30/max_execution_time = 360/g' /etc/php/7.3/apache2/php.ini

echo creating database
mysql --user="root" --password="invoiceninja" --execute="CREATE DATABASE invoiceninja;"
mysql --user="root" --password="invoiceninja" --execute="CREATE USER 'invoiceninja'@'localhost' IDENTIFIED BY 'invoiceninja';"
mysql --user="root" --password="invoiceninja" --execute="GRANT ALL ON invoiceninja.* TO 'invoiceninja'@'localhost' IDENTIFIED BY 'invoiceninja' WITH GRANT OPTION;"
mysql --user="root" --password="invoiceninja" --execute="FLUSH PRIVILEGES;"

echo installing invoiceninja
cd /var/www/html
git clone https://github.com/invoiceninja/invoiceninja.git
cd /var/www/html/invoiceninja
composer install

echo installing nodejs
curl -sL https://deb.nodesource.com/setup_10.x | bash -
apt install -y nodejs

echo installing puppeteer
npm install puppeteer

echo setting permissions
chown -R www-data:www-data /var/www/html/invoiceninja/
chmod -R 755 /var/www/html/invoiceninja/

echo adding virtual host
cat > /etc/apache2/sites-available/invoiceninja.conf << EOL
<VirtualHost *:80>
     ServerAdmin admin@example.com
     DocumentRoot /var/www/html/invoiceninja/public
     ServerName invoiceninja.local
     ServerAlias www.invoiceninja.local

     <Directory /var/www/html/invoiceninja/public>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
     </Directory>

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
EOL

echo disabling default site
a2dissite 000-default.conf

echo enabling invoiceninja site
a2ensite invoiceninja.conf

echo enabling rewrite module
a2enmod rewrite

echo restarting apache
systemctl restart apache2.service

echo configuring invoices cronjob
cat > /etc/cron.d/invoices << EOL
0 8 * * * root /usr/local/bin/php /var/www/html/invoiceninja/artisan ninja:send-invoices
EOL

echo configuring reminders cronjob
cat > /etc/cron.d/reminders << EOL
0 8 * * * root /usr/local/bin/php /var/www/html/invoiceninja/artisan ninja:send-reminders
EOL

echo installation complete
